services:

  postgres:
    image: postgres:16
    container_name: postgres
    environment:
      POSTGRES_USER: customer
      POSTGRES_PASSWORD: customer
      POSTGRES_DB: customer
    ports:
      - "5432:5432"
    volumes:
      - postgres:/var/lib/postgresql/data
    networks:
      - infra
    restart: always


  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - infra
    restart: always
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  zipkin:
    image: openzipkin/zipkin
    container_name: zipkin
    ports:
      - "9411:9411"
    networks:
      - infra
    restart: always



networks:
  infra:

volumes:
  postgres: